// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./src/components/home/home copy 2.vue')['default']
    3: typeof import('./src/components/home/home copy 3.vue')['default']
    copy: typeof import('./src/components/home/home copy.vue')['default']
    Found: typeof import('./src/components/home/found.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeBar: typeof import('./src/components/homeBar.vue')['default']
    Mine: typeof import('./src/components/home/mine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/home/user.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
  }
}
